-- Seed data: default admin + a couple of starter templates.
-- The admin password hash is generated by the API on first boot if missing;
-- this seed inserts only non-secret template rows. Run after schema.sql.

INSERT OR IGNORE INTO templates (id, key, name, wedding_type, payload, active) VALUES
  ('tpl-traditional', 'budget', 'باقة تقليدية', 'traditional', '{"goldBoost":1.2}', 1),
  ('tpl-modern',      'budget', 'باقة عصرية',   'modern',      '{"musicBoost":1.25}', 1),
  ('tpl-luxury',      'budget', 'باقة فاخرة',    'luxury',      '{"venueBoost":1.3}', 1);
